#!/bin/bash

cd /var/run/varnishstats

echo "installing python virtual environment"
python3 -m venv .venv
source .venv/bin/activate

echo "installing python requirements"
pip install -r requirements.txt > /dev/null 2>&1

echo "running vanishtstats-exporter"
timestamp=$(date +s%)
python varnishstats-exporter.py > varnishstats.${timestamp}.log 2>&1

exit $?
